// Pick is a Whitelist: You specify exactly what you want to keep.
// Use this when: You have a large object, but you only need a small slice
// of it (e.g., a summary card in a UI).

// Omit is a Blacklist: You specify exactly what you want to discard.
// Use this when: You want the entire object, but need to remove just one or two specific things
// (e.g., sensitive data or fields generated by the backend).

interface Employee {
  id: number;
  name: string;
  email: string;
  salary: number; // Confidential
  passwordHash: string; // Confidential
}

// Scenario: Displaying a list of employees on a dashboard
// We don't need (and shouldn't have) salary or password here.
type EmployeeSummary = Pick<Employee, "id" | "name" | "email">;

const summary: EmployeeSummary = {
  id: 101,
  name: "Alice",
  email: "alice@company.com",
  // salary: 50000 // ERROR: Object literal may only specify known properties
};

interface BlogPost {
  id: string; // Generated by DB
  title: string;
  content: string;
  tags: string[];
  createdAt: Date; // Generated by DB
}

// Scenario: A form to create a NEW blog post
// The user provides title, content, and tags.
// They do NOT provide 'id' or 'createdAt'.
type CreatePostInput = Omit<BlogPost, "id" | "createdAt">;

const newPost: CreatePostInput = {
  title: "TypeScript Tips",
  content: "Here is how to use Omit...",
  tags: ["coding", "ts"],
  // id: "123" // ERROR: 'id' does not exist in type 'CreatePostInput'
};
